"""AGENTS.md Context Generator for AI Pair Programming Assistants."""

from pathlib import Path
from typing import Optional, Union

from stackbridge.core.graph import StackGraph


class AgentContextGenerator:
    """Generates structured AGENTS.md documentation mapping cross-stack boundaries for coding agents."""

    @staticmethod
    def generate_agents_md(graph: StackGraph, repo_path: Union[str, Path] = ".") -> str:
        """Generates markdown documentation of the cross-stack dependency graph."""
        graph_dict = graph.to_dict()
        nodes = graph_dict.get("nodes", [])
        edges = graph_dict.get("edges", [])

        fe_nodes = [n for n in nodes if n.get("type") in ("frontend", "frontend_component")]
        be_nodes = [n for n in nodes if n.get("type") in ("route", "api_route")]
        db_nodes = [n for n in nodes if n.get("type") in ("model", "schema_model")]

        lines = [
            "# AGENTS.md — StackBridge AI Agent Architecture Guide",
            "",
            "> Automated full-stack AST boundary map generated by **StackBridge-MCP**.",
            "",
            "## 1. System Topology Overview",
            f"- **Total Dependency Nodes:** {len(nodes)}",
            f"- **Total Cross-Boundary Edges:** {len(edges)}",
            f"- **Frontend Client Calls:** {len(fe_nodes)}",
            f"- **Backend API Routes & MCP Tools:** {len(be_nodes)}",
            f"- **Database ORM Models:** {len(db_nodes)}",
            "",
            "## 2. Full-Stack Boundary & Route Matrix",
            "",
            "| Type | Endpoint / Target | Methods | Source File | Handler / Symbol | Referenced Models |",
            "| :--- | :--- | :--- | :--- | :--- | :--- |",
        ]

        for r in be_nodes:
            methods = r.get("http_methods") or [r.get("http_method", "GET")]
            methods_str = ", ".join(methods) if isinstance(methods, list) else str(methods)
            norm_path = r.get("normalized_path") or r.get("raw_path") or r.get("id", "")
            file_p = r.get("file_path", "")
            func_name = r.get("function_name", "handler")
            models_ref = ", ".join(r.get("orm_models_referenced", [])) or "—"
            route_type = "MCP Tool" if "MCP" in methods_str else "FastAPI Route"

            lines.append(
                f"| {route_type} | `{norm_path}` | `{methods_str}` | `{file_p}` | `{func_name}()` | {models_ref} |"
            )

        lines.extend([
            "",
            "## 3. Database Schema & ORM Models",
            "",
            "| Model Name | Table Name | Source File | Fields |",
            "| :--- | :--- | :--- | :--- |",
        ])

        for m in db_nodes:
            c_name = m.get("class_name") or m.get("id", "").split("::")[-1]
            t_name = m.get("table_name") or c_name.lower()
            file_p = m.get("file_path", "")
            m_fields = m.get("fields", [])
            field_names = ", ".join([str(f.get("name")) for f in m_fields if isinstance(f, dict) and f.get("name") is not None]) or "—"

            lines.append(
                f"| `{c_name}` | `{t_name}` | `{file_p}` | `{field_names}` |"
            )

        lines.extend([
            "",
            "## 4. MCP Server Tools for Coding Agents",
            "",
            "StackBridge exposes high-ergonomics JSON-RPC 2.0 MCP tools for AI agents:",
            "- `trace_fullstack_path(symbol_or_path)`: Trace complete dependency graph across UI, routes, and DB.",
            "- `get_route_contract(route_path, method)`: Extract complete request/response contracts and status codes.",
            "- `verify_schema_change(modified_files)`: Run zero-false-positive AST breakage verification before edits.",
            "- `verify_breakage(modified_files)`: Diagnostic compiler checks with formatted agent recommendations.",
            "- `get_stack_health()`: Real-time fullstack error and drift statistics.",
            "",
            "## 5. Agent Safety Guidelines & Guard Rules",
            "",
            "1. **Never edit an ORM model field** without checking upstream FastAPI response models and TypeScript fetch callers.",
            "2. **Run the pre-commit guard** before committing any changes:",
            "   ```bash",
            "   python -m stackbridge.main guard --repo-path .",
            "   ```",
            "3. **Predict test impact** before executing test suites to isolate impacted test callers.",
            "",
        ])

        return "\n".join(lines)

    @classmethod
    def write_agents_md(
        cls,
        repo_path: Union[str, Path] = ".",
        output_path: Optional[Union[str, Path]] = None,
        graph: Optional[StackGraph] = None,
    ) -> str:
        """Builds graph (if not provided) and writes AGENTS.md to disk."""
        active_repo = Path(repo_path).resolve()
        active_graph = graph or StackGraph.build_from_repo(str(active_repo))

        content = cls.generate_agents_md(active_graph, repo_path=active_repo)
        dest = Path(output_path).resolve() if output_path else active_repo / "AGENTS.md"

        dest.parent.mkdir(parents=True, exist_ok=True)
        with open(dest, "w", encoding="utf-8") as f:
            f.write(content)

        return str(dest)
